[package]
name = "RatioUp"
author = "slundi"
version = "1.1.2"
edition = "2021"
homepage = "https://github.com/slundi/RatioUp"

[source.vendored-sources]
directory = "vendor"

[dependencies]
regex = "1.9"
rand = "0.8"
lazy_static = "1.4" # to remove, OnceCell in std replace it
serde = {version = "1", features = ["derive"]}
serde_json = "1"
ureq = { version = "2", features = ["charset", "gzip"]}
tokio = {version = "1.32", features=["fs"]}
futures-util = { version = "0.3", default-features = false, features = ["std"] }
sanitize-filename = "0.5"
uuid = { version = "1", features = ["v4"] }
byte-unit = "4"
url = "2"
fake-torrent-client = "0.9"

rust-ini = "0.19"
dotenv = "0.15"
log = "0.4"
simple_logger = "4"

#bittorrent parsing
serde_bytes = "0.11"
serde_bencode = "0.2"
serde_derive = "1"
hmac-sha1-compact = "1"
hex = "0.4"

# actix
actix = "0.13"
actix-web = "4"
actix-files = "0.6"
actix-multipart = "0.6"
actix-rt = "2"
