[package]
name = "RatioUp"
author = "slundi"
version = "1.1.0"
edition = "2018"
homepage = "https://github.com/slundi/RatioUp"

[source.vendored-sources]
directory = "vendor"

[dependencies]
regex = "1.6"
rand = "0.8"
lazy_static = "1.4"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
ureq = { version = "2", features = ["charset", "gzip", "brotli"]}
tokio = {version = "1.21", features=["fs"]}
futures-util = { version = "0.3", default-features = false, features = ["std"] }
sanitize-filename = "0.4"
uuid = { version = "1", features = ["v4"] }
byte-unit = "4"
url = "2"
fake-torrent-client = "0.9"

rust-ini = "0.18"
dotenv = "0.15"
log = "0.4"
simple_logger = "4"

#bittorrent parsing
serde_bytes = "0.11"
serde_bencode = "0.2"
serde_derive = "1"
sha1 = "*"
hex = "0.4"

# actix
actix = "0.13"
actix-web = "4"
actix-files = "0.6"
actix-multipart = "0.4"
actix-rt = "2"

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.jemallocator]
version = "0.5"
