[package]
name = "RatioUp"
version = "0.1.0"
edition = '2018'

[dependencies]
rand = "*"
rand_regex = "*"
#lazy_static = "*"
serde = "*"
serde_json = "*"
lava_torrent = "*"
regex = "*"
reqwest = { version = "*", features = ["json"] }
globset = "*"
actix = "*"
actix-web = "*"
actix-files = "*"
actix-web-actors = "*"
clap = "*"
