[package]
name = "RatioUp"
version = "0.1.0"
edition = '2018'

[dependencies]
lazy_static = "*"
serde_json = "*"
lava_torrent = "*"
regex = "*"
reqwest = { version = "*", features = ["json"] }
globset = "*"
