name: Rust

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      if: startsWith(github.ref, 'refs/tags/')

    - name: Upload to Pixeldrain
      id: upload-to-pixeldrain
      run: |
        RESPONSE=$(curl -T "./target/debug/RatioUp" https://pixeldrain.com/api/file/)
        UPLOAD_ID=$(echo $RESPONSE | jq -r '.id')
        echo "::set-output name=upload_id::$UPLOAD_ID"
      if: startsWith(github.ref, 'refs/tags/')

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }} (Debug)
        body: |
          Debug binary uploaded to Pixeldrain: https://pixeldrain.com/u/${{ steps.upload-to-pixeldrain.outputs.upload_id }}
        draft: false
        prerelease: true
      if: startsWith(github.ref, 'refs/tags/')
