name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE: slundi/ratioup
  PLATFORMS: linux/arm/v7,linux/arm64,linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
#multi-arch: https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: docker/setup-buildx-action@v1
    - name: Docker meta
      id: meta # you'll use this in the next step
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGE }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ env.PLATFORMS }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

